notifications:
    email: false

sudo: false

os:
  - osx
  - linux

language: node_js

node_js:
  - "6.3.1"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish

script:
  - npm test --silent

after_success:
  - if [ "$TRAVIS_BRANCH" == "release" ]; then
      npm install -g vsce
      vsce package
      vsce publish -p $VS_TOKEN
    fi

deploy:
  provider: releases
  api_key:
    secure: IccNv4d/b3/c2Wg/A39L/gfNPT0nBMpcf2b5PlEy+U79ii9hKHq681hHCJ/NPhwUjWOfSfgFXRoTJVYIHuMnT7WLnSqfqiiPUo82z0ulZQOEEdt8oVHoABm5SzAPQqe6Lo/SC+2zYV6TgqP/i9qVN0TuyA1jH00hmpBjnozO98GyuJIeUYwvEBkhJttcO0HLb836td5OxG8SDRo9kFauITNZAFQA8yVlsFmCJF1Di7Oncmcjcd5aHm9PnbgQytHg+iWMhBZuHXfB9hV4J0tsMZB+XPxvkS74dASuKjEIIdB66GXoVL5BzJmopY3gQVYpK5wK+HH4PwwpdZ1BY0qW4zmUCwwlNXSIVX8IjCiRt/5Bc3hqpY8zahIFKW37ZbHSVH1kKK9+fmEt5iy4HSqGGxmSXVrQGY1VJhsol/0Yu326L9J35AKhQeYKQvIdUQy4LiIN8NTUtEZr5Nvv6+TCI0RShQgkGQrlVyknIpoq9HM915NDTRLwm3s78LptkOP6wmRk26HLOBdYG/0k15Wos7mtR6cXc+NqKZm8tPfPEn2cIzGrmQgKXuCoXu+hGoOl/2HSzDnUUxhiSVbjoCei7HRXPT+0yhDc8e+Kt1fHKDJpyj7ybICVGmexxQY41mPtAVKrX/pDBCi53QVT1a+QEAd5Y27X4S8Ko+Vqukkoq7E=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    branch: release
    repo: jpoon/vscode-typewriter
    tags: true

env:
  global:
    secure: awRYn5Bvp5GNYlkKiaMSMng6n5MrePToMQsBKtFaUvh/BXt5Fk416AhGMjqPxd5XdQdMOoisMnjvYTUd2ykz7MRPmhMfOlhrueoiCXXI5BMPMOc8NNnz0c1/Jd88HXyMccfdS3D3AVjdNDpeYQh9/xUicFx0XSgYsGqz6yWAjfy8zhn77GLWwkDYqSWLTiLbL2/Us41gScNIJoqPHMO17nw6zftnvRNKbXvTAhcbNZdaf5ZfALiCyo1xqRbNL6EWL67gNJyw/eSt/uq+30gRFyRcT8aqFCbesvr5eAvMLfrYB3LDNWdXY4nRCduAtEyxlhCgx5G9Zu5BCvul1vu7c8UAmzBd6Pi0JPBGcKIu+ZV3K1UhSiIuH+zep1MYMRappz1ZPYrhG93r4tJx83OLhMoiGeWHLXKOJhIwCqEeFxp8B4eOPlYW7ciYG/AvcvoQJhmVfvrd6xoSsEDb9FkKC/7733Vvubt30AarKvK1GF7wJepKpbp5IJfKhxMbaHSEm9FP1xa1jvu7QtUGcf3iROu0XCm+QPQzAANyArA/CoZR7I6lhRwRz2tpPn4xWEW08QdARPSdCFsaGyVJEgrkmRDyUpjFoan3tI4PPq7aotoL5c4Di8Ld5e1q/vgGgA58Y64vIOWjYDzP2beNkZexY61QxZrJo80/gddD3nN3j2M=
